version: '3.8'

services:
  frontend:
    image: caicongyang/stocker-front:latest
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=/api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - ai-backend
    networks:
      - app-network

  backend:
    image: caicongyang/stock:latest
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

  ai-backend:
    image: caicongyang/financial-engineering:latest
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
