version: '3.8'

services:
  frontend:
    image: caicongyang/stocker-front:latest
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=/api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf